from pathlib import Path
import json, re, hashlib
root=Path('/Users/pat/code/rho_aif')
s=(root/'paper/full_paper_jair.tex').read_text()
l=(root/'paper/full_paper.tex').read_text()
proposals=[]
def add(id, old, new, rationale, evidence):
    assert s.count(old)==1, (id,s.count(old))
    # Scientific prose is identical across the masters. Description-free figure
    # blocks are recorded separately where the venue differs.
    item=dict(id=id,old=old,new=new,rationale=rationale,retained_evidence=evidence)
    if l.count(old)!=1:
        alternative=re.sub(r'\\Description\{[^\n]*\}\n','',old)
        assert l.count(alternative)==1, (id,l.count(old),l.count(alternative))
        item['old_lncs']=alternative
        item['new_lncs']=re.sub(r'\\Description\{[^\n]*\}\n','',new)
    proposals.append(item)
def block(start,end):
    a=s.index(start); b=s.index(end,a);return s[a:b].rstrip()
add('theory-01',
'This appendix gives the details behind the budgeted experiments that the main text summarizes. It records how the SARSOP models were built and exported, proves the factorization property the distractor-diagnosis environment relies on, and presents the atlas of measured shadow prices.',
'', 'Remove an appendix roadmap duplicated by its three subsection headings.', 'All three subsections and their cross-reference labels remain.')
add('theory-02',block("Section~\\ref{sec:sarsop}'s reference solver",'\\subsection{Distractor-Diagnosis'),r'''The reference uses the original APPL C++ solver \texttt{pomdpsol}, built by \url{tools/build_sarsop.sh} with four documented Apple-Silicon/clang compatibility patches. The binary is not committed. \url{experiments/run_sarsop_baseline.py} exports each discrete observe-then-commit benchmark from the agents' own state, action and observation definitions, adding an absorbing done state and discount $\gamma=0.999$. It solves to precision $10^{-3}$, parses the XML alpha vectors and evaluates their policy through the shared episode runner. \url{tests/test_sarsop_export.py} checks the exporter, parser and argmax agent without the solver binary.''',
'Keep the complete solver/export/evaluation specification and executable provenance while removing implementation narration.',
'Original solver identity, build and runner paths, common model definitions, absorbing state, discount, solve precision, alpha-vector parsing, common evaluator, and binary-independent tests.')
add('theory-03',block("Section~\\ref{sec:distractor}'s \\texttt{DistractorDiagnosisEnv}",'\\subsection{The $w^*$ Atlas}'),r'''\texttt{DistractorDiagnosisEnv} has a four-way condition $x$ and binary nuisance $z$. Each test observes one factor, terminal rewards depend only on $x$, and rewards are not observations. For a factored belief $b(x,z)=b_X(x)b_Z(z)$ and a nuisance likelihood $L(o\mid z)$, Bayes' rule gives
\[
b'(x,z\mid o)=b_X(x)\frac{L(o\mid z)b_Z(z)}{\sum_{\tilde z}L(o\mid\tilde z)b_Z(\tilde z)}.
\]
Thus the condition marginal is unchanged. Condition tests preserve the nuisance marginal by the same argument. The independent generative process preserves this factorization, but correlated beliefs, including those caused by misspecification, are outside the guarantee. \url{tests/test_distractor_diagnosis.py} checks both marginal identities numerically.''',
'Replace repeated verbal proof and test narration with one explicit Bayes factorization.',
'Independent prior hypothesis, single-factor likelihoods, condition-only reward/no reward observations, both marginal invariances, correlated-belief exclusion, test provenance. The new equation is the original verbal argument written explicitly, not a new claim.')
add('theory-04',block('Table~\\ref{tab:w-atlas} collects','% Table auto-generated by experiments/run_w_atlas.py'),r'''Table~\ref{tab:w-atlas} reports eight measured usage ranges, their implicit EFE budgets $B_{\mathrm{EFE}}=U(1)$, and crossing brackets at two fixed relative positions within each range (Definition~\ref{def:pi3}). \url{experiments/run_w_atlas.py} produces it from \texttt{results\_\allowbreak price\_\allowbreak usage\_\allowbreak curves.csv} and \texttt{results\_\allowbreak price\_\allowbreak interleaved\_\allowbreak curves.csv}. The table compares operating points, not a closed-form relationship between budget and environment parameters.''',
'Remove repeated definitions of range-relative targets and an extended warning already expressed in the final sentence.',
'All eight atlas instances/table rows retained, EFE budget, grid-bracket meaning, calibration-derived relative targets, source CSVs/producer, and no closed-form generalization.')
add('theory-05',
'This appendix retains the derivations, boundary examples, and implementation qualifications supporting Sections~\\ref{sec:methodology} and~\\ref{sec:budget}.','',
'Remove a roadmap repeated by the appendix title and headings.', 'All detailed derivations and labels remain.')
old=block('\\begin{figure}[tbp]\n\\centering\n\\includegraphics[width=\\linewidth]{figures/fig_otc_loop.pdf}','Proposition~\\ref{prop:equivalence} covers one specific formulation')
add('theory-06',old,'','Remove the unreferenced observe-then-commit schematic, which repeats the main setup and engineer-facing workflow. Retain its producer and figure files in the repository.',
'State preservation, paid observations, terminal non-observing commitment and horizon/replanning distinctions all remain explicitly in the main method and proofs. No experimental evidence is removed.')
add('theory-07',block('Proposition~\\ref{prop:equivalence} covers one specific formulation','\\subsection{Two-State Thresholds'),r'''Equation~\ref{eq:efe_recursive} uses recursive closed-loop EFE associated with sophisticated inference \citep{friston2021,dacosta2020b}, specifically the information-gain and pragmatic-value formulation related by \citet{champion2024}. We do not establish its $w=1$ coefficient for Free Energy of the Expected Future \citep{millidge2021}, generalised free energy \citep{parr2019}, epistemic-prior variational inference \citep{devries2025}, or the Bethe-Lagrangian formulation \citep{kouw2026bethe}.

The reward--information qualification is given in Section~\ref{subsec:formal_rho_equiv}. Log scoring gives the exact normalized case ($Z=1$). Otherwise Proposition~\ref{prop:equivalence} concerns the reward-based recursion conditional on its pragmatic identification, since $-T\ln Z$ can depend on policy when episode lengths differ. The implementation separately adopts one reward unit per bit, and Appendix~\ref{app:nat_canonical} tests the nat-canonical weight $w=\ln2$. Proposition~\ref{prop:pi1} handles positive reward-and-cost rescaling. None of these claims makes $w=1$ universally reward-optimal.''',
'Consolidate almost two pages of duplicated unit/normalizer exposition into an explicit scope summary pointing to the complete main-text derivation.',
'Every cited alternative EFE formulation remains named. Exact log score, conditional recursion, policy-dependent normalizer, bit convention and nat-canonical test remain separate. The full derivation, conversion values, empirical results and reward-scaling argument remain in the main text and named appendices.')
add('theory-08',
'The two parts of Proposition~\\ref{prop:nearopt} concern distinct horizons. We retain the derivation and descriptive comparisons here.','',
'Remove a redundant introduction because the proposition identifies both horizons.', 'H=1 versus H=2 scope retained in the proposition.')
add('theory-09',block('Consider a two-state observe-then-commit $\\rho$-POMDP with uniform prior', '\\textbf{Part (a)'),r'''Consider a two-state observe-then-commit $\rho$-POMDP with uniform prior, one observation action of accuracy $\tfrac12<p\le1$ and cost $c>0$, and two commit actions paying $R^+>0$ when correct and $R^-<0$ otherwise, with $|R^-|>R^+$. Write $\alpha=|R^-|/R^+$, $\eta=I_{\max}/c$ and
\[
I_{\max}=\ln2-H_{\mathrm{post}}(p),\qquad
H_{\mathrm{post}}(p)=-p\ln p-(1-p)\ln(1-p).
\]
Information is measured in nats. Part (a) concerns one observation followed by commitment ($H=1$), and Part (b) allows a second observation ($H=2$) and requires $p<1$.''',
'Condense repeated definitions of the uniform-prior entropy reduction and the distinct horizons.',
'All original model hypotheses, reward signs/asymmetry, accuracy bounds, cost, unit conventions and definitions retained. The perfect-sensing limit is retained in proposal theory-10.')
add('theory-10',block('At $H{=}2$ for this two-state case','\\end{proposition}\n\n\\begin{proof}[Proof sketch]'),r'''In this symmetric model $\mathrm{VoI}_2(b)=0$, because a disconfirming second observation returns the posterior to the tie point. Thus the finite branch applies. If $w^*_{\mathrm{thresh}}\le0$, every $w\in(w^*_{\mathrm{thresh}},w^*_{\mathrm{over}})\cap[0,\infty)$ reproduces the reward-optimal single observation. We call this the near-optimality interval. Weights above $w^*_{\mathrm{over}}$ buy an instrumentally unprofitable second observation. If $w^*_{\mathrm{thresh}}>0$, immediate commitment is reward-optimal. Weights inside the interval instead buy one observation at reward loss $c-(p-\tfrac12)(R^+-R^-)$, strictly between zero and $c$. These statements do not extend to longer horizons. Part (a) includes perfect sensing under $0\ln0=0$, giving $I_{\max}=\ln2$. Part (b) excludes it because $I(b)=0$ makes the upper ratio undefined.''',
'Remove repeated interpretations and discussion of an infinite branch that cannot occur under the stated symmetric model; retain the general displayed branch definition unchanged.',
'The strict interval, nonnegative weights, both threshold-sign regimes, positive regret bound, symmetric zero-VoI identity, upper-threshold meaning, distinct horizons and perfect-sensing boundary all remain.')
add('theory-11',block('\\begin{proof}[Proof sketch]\n\\emph{Part (a).}', '\\end{proof}\n\nUnder the paper\'s reward convention'),r'''\begin{proof}
For Part (a), immediate commitment has value $(R^++R^-)/2$, while observing once and committing has value $-c+wI_{\max}+pR^++(1-p)R^-$. Their difference is
\[
(p-\tfrac12)(R^+-R^-)-c+wI_{\max}.
\]
Solving the strict positivity condition and substituting $R^-=-\alpha R^+$ gives the stated threshold and asymmetry condition.

For Part (b), the second observation's advantage at $b=(p,1-p)$ is $-c+wI(b)+\mathrm{VoI}_2(b)$. A confirming observation has probability $q=p^2+(1-p)^2$ and posterior maximum $p^2/q$. A disconfirming observation has probability $2p(1-p)$ and posterior maximum $1/2$. Their expected maximum is $p^2+p(1-p)=p$, so the expected best commit reward is unchanged and $\mathrm{VoI}_2(b)=0$. The second observation is therefore rejected below $w^*_{\mathrm{over}}=c/I(b)$. Combining this with Part (a) gives the stated interval and reward loss.''',
'Compress repeated Bellman expressions while making the previously asserted zero-VoI identity explicit.',
'Both complete arguments remain: comparison of immediate/one-observation value, threshold algebra, second-observation value and zero-VoI derivation, interval and regret. End-proof delimiter remains outside the replacement.')
add('theory-12',block("Under the paper's reward convention, $w{=}1$ lies in this interval",'\\begin{table}[ht]\n\\centering\n\\caption{Reward asymmetry ($\\alpha$)'),r'''Only Tiger in Table~\ref{tab:alpha_eta} satisfies the proposition's two-state and strict-asymmetry hypotheses. Diagnosis and Tileworld use an unproved two-state reduction retaining observation accuracy, sensing cost and correct/incorrect rewards while discarding state and test counts. Those parameters coincide for the two domains, hence their identical rows. Testbed has $|R^-|=R^+$ and is included descriptively. The table compares these thresholds with the Pareto sweep's reward-maximizing weights.''',
'Remove repeated table-column descriptions and repeated explanations of the heuristic reduction.',
'Tiger-only formal applicability, unproved multi-state reductions, exact retained/discarded model features, reason for equal rows and Testbed boundary exclusion.')
oldstart='\\caption{Reward asymmetry ($\\alpha$), informativeness ($\\eta$ in nats per reward unit)'
old=block(oldstart,'\\label{tab:alpha_eta}')
add('theory-13',old,r'''\caption{Two-state thresholds in reward units per nat, with reward-maximizing weights $w^*_{\mathrm{ret}}$ in reward units per bit. The $w=1$ column uses nat units, whereas implemented $w=1$ equals $1/\ln2\approx1.44$ reward units per nat. Bracketed entries are closed ranges of tied maximizing grid weights, not budget-crossing brackets. The eleven-weight grid of Section~\ref{sec:pareto} is evaluated for $500$ episodes per seed over five seeds (\texttt{results\_\allowbreak pareto\_\allowbreak sweep.csv}). Only Tiger satisfies the proposition's hypotheses.}''',
'Keep caption interpretability while moving no evidence: the grid/protocol are already specified at the referenced source.',
'Table values unchanged, nat/bit distinctions, 1.44 conversion, exact tied-grid ranges versus crossing brackets, experiment archive/protocol and formal-scope restriction.')
add('theory-14',block('Table~\\ref{tab:alpha_eta} shows two patterns.','\\paragraph{Extension to discounting.}'),r'''The finite-horizon interval is descriptive for the longer-horizon sweep. Testbed's upper threshold is approximately $1.01$ reward units per nat, placing nat-canonical $w=1$ inside and implemented $w=1$ outside. Yet at $H=4$ the two implementations have identical reward, success and usage (\texttt{results\_\allowbreak nat\_\allowbreak canonical\_\allowbreak check.csv}) and both over-observe relative to $w^*_{\mathrm{ret}}\in[0.01,0.5]$. On Tiger and Diagnosis, $w=1$ belongs to the observed reward-maximizing range. Tileworld contradicts that extrapolation: its unique sampled optimum is $w=20$ in bit units ($28.9$ per nat), above the heuristic upper threshold $7.91$, and $w=1$ is Pareto-dominated.''',
'Remove two repetitions of table cells and the repeated distinction between formal and descriptive cases.',
'Adverse Testbed and Tileworld results retained with units, horizon and source archive. Tiger/Diagnosis agreement remains descriptive. No finite-horizon interval is promoted to a longer-horizon guarantee.')
add('theory-15',block('\\paragraph{Extension to discounting.}','\\subsection{State-Preservation Proof'),r'''\paragraph{Discounting.} Applying $\gamma<1$ consistently preserves the algebraic equivalence:
\[
-\mathcal G(\mathrm{observe}_k,b)=-c_k+I_k(b)+\gamma\,\mathbb E_o[\max_a V(a,b'_o)].
\]
Current information gain is immediate while the eventual commit reward is discounted. This increases the epistemic share along a branch but need not increase sensing, because the entire continuation is discounted relative to committing now. Diagnosis uses $5.83$ observations at $\gamma=0.95$ versus $9.68$ at $\gamma=1$ (Table~\ref{tab:discount}). Appendix~\ref{app:discount} gives the same-horizon EFE/Planning comparison.''',
'Replace repeated recursive formulas and intuition with one equation and its relevant qualification.',
'Consistent discounting, immediate information versus delayed reward, no monotone exploration claim, actual opposite empirical effect and comparison provenance.')
add('theory-16',block('Proposition~\\ref{prop:factored} extends the formal bridge','\\begin{remark}[The scope restriction'),r'''The branch identity is preserved under arbitrary interleaving of observation and navigation actions because both preserve the hidden state. It does not cover arbitrary exploitation transitions. Terminal exploitation has no successor belief. Nonterminal exploitation has zero information gain here because its observation is uninformative and rewards are not used for belief updates. A model that conditions on payoffs must include their information gain. RockSample agents mark sampled rocks unavailable but never infer quality from the sampling payoff (\texttt{rho\_\allowbreak aif/\allowbreak agents/\allowbreak rocksample\_\allowbreak agents.py}).

The hypothesis can model non-destructive testing or spatial sensing of a quantity held fixed over the decision horizon. It must be checked for the particular action and horizon, rather than inferred from an application name. Example~\ref{ex:destructive} shows what can fail when sensing changes that quantity.''',
'Consolidate four repetitive paragraphs already stated in the main method, preserving the important exploitation-channel qualification. Replace a generic application taxonomy with an explicitly conditional sentence.',
'Observation/navigation-only extension, no arbitrary exploitation guarantee, terminal versus nonterminal rationale, rewards-not-observations, payoff-conditioned alternative and exact RockSample implementation behavior.')
add('theory-17',block('\\begin{remark}[The scope restriction', '\\begin{table}[ht]\n\\centering\n\\caption{Taxonomy'),r'''\begin{remark}[Transition-aware information gain]
\label{rem:transition-aware}
Example~\ref{ex:destructive} limits the state-preserving reduction, not EFE with correct transition dynamics. Under our observe-then-transition timing, use
\[
b'_{o,T}(s')\propto\sum_s T(s'\mid s,a)O(o\mid s,a)b(s)
\]
and the corresponding predictive distribution when computing post-transition information gain. In the example both are concentrated at state $0$, giving zero information gain and the reward-only value $1-c$. In general genuine information about the post-transition state can remain. A nonzero $\Delta_T$ witnesses failure of state preservation, but zero does not establish it. The diagnostic is neither an established additive value correction nor a decision-error bound. Extending the budget procedure to these dynamics, or proving a perturbation bound, remains open.
\end{remark}''',
'Eliminate repeated defenses of EFE while preserving the corrected timing, distributions and all diagnostic limitations.',
'Observe-before-transition convention, exact joint posterior, corresponding predictive distribution, zero-information destructive case, genuine post-transition information, one-way diagnostic and no error-bound/tracking extension claims.')
add('theory-18',block('\\begin{table}[ht]\n\\centering\n\\caption{Taxonomy','\\subsection{Agent Specifications'),'',
'Remove a generic application-name taxonomy whose structural labels depend on model choices; retain its careful replacement in theory-16.',
'No empirical or mathematical evidence removed. The state-preserving definition, proof and full destructive counterexample remain.')
add('theory-19',block('The scale-equivariance and comparative-statics proofs appear','\\begin{proof}\nAt $H{=}1$'),'','Remove introductory signposting that duplicates the subsection heading and main theorem cross-references.', 'The onset proof and complete main scale/comparative-statics proofs remain unchanged.')
add('theory-20',block('The corollary is verified numerically','\\subsection{Proof and Implementation Scope'),r'''\texttt{TestProp2OnsetExact} in \url{tests/test_budget.py} checks the onset with the implemented $H=1$ planner over complete receding-horizon episodes. It therefore asserts zero usage below the threshold and at least one observation above it, rather than the one-shot proof's exact usage of one. For a Testbed with $p=0.6$, $c=0.3$ and rewards $\pm1$, the threshold is approximately $3.44$ in bit units. The test uses weights $0.9$ and $1.2$ times that threshold. Appendix~\ref{sec:prop2exp} gives refined-grid checks on two instances.''',
'Shorten numerical-check narration without removing its crucial one-shot versus receding-horizon distinction.',
'Exact test and model, units, threshold and tested multipliers, zero/at-least-one assertions, and refined-grid evidence.')
add('theory-21',block('\\begin{figure}[tbp]\n\\centering\n\\includegraphics[width=\\linewidth]{figures/fig_dual_feedback.pdf}','Proposition~\\ref{prop:pi5} covers the projected'),'','Remove the unreferenced feedback schematic duplicating the main controller equation, sign explanation and scope paragraph. Keep the producer and PDF in the repository.',
'Controller equation, projection/sign logic, stationary hypotheses, gap-budget distinction, reset/default exclusions and full proof remain in the manuscript.')
add('theory-22',block('Proposition~\\ref{prop:pi5} covers the projected','The recursion originates with'),r'''The implementation and its three variants are specified in Section~\ref{sec:pi5}. Only the projected decaying-step variant is covered below. The reported parameters are implemented by \texttt{DualWeightAgent} in \texttt{rho\_\allowbreak aif/\allowbreak agents/\allowbreak dual\_\allowbreak descent.py} and \texttt{dual\_\allowbreak update} in \texttt{rho\_\allowbreak aif/\allowbreak budget.py}.''',
'Refer to the complete main scope statement instead of repeating all parameters, observed maximum and excluded defaults.',
'Main text explicitly retains finite upper projection, delta .02/wmax100, maximum3.1, released constant-step/no-upper-projection default, and reset exclusion; exact code provenance retained.')
# Preserve both controller-proof paragraphs verbatim. Trim only text after the running-average conclusion.
add('theory-23',block('Under a constant step, which no reported run uses','\\subsection{Relationship to Constrained Planning'),'The constant-step default and reset-on-shift runs require separate arguments (Section~\\ref{sec:pi5}). The re-adaptation results of Section~\\ref{sec:dual_multiseed} are empirical. The proof requires a single sign-consistent crossing and does not cover arbitrary nonmonotone usage curves.',
'Remove repeated constant-step intuition, reset heuristic specification and theorem-scope discussion already fully present in the main controller subsection.',
'Full supermartingale and Kronecker proof unchanged, including interior crossing and vanishing increment logic. No constant-step or nonstationary tracking guarantee. Reset implementation remains described in main.')
add('theory-24',block('The calibrated $w$ meets a sensing target within Planning+IG','\\FloatBarrier\n\\section{Extended Experimental'),r'''The calibrated information weight is not the multiplier of the sensing cap. Classical resource-price adaptation includes constrained MDPs \citep{altman1999}, Shannon-capacity and costly-information models \citep{sims2003,matejka2015}, and SAC's entropy-temperature dual gradient descent \citep{haarnoja2018sac}. The last supplies the feedback pattern for Equation~\ref{eq:dual_update}, with sensing usage replacing policy entropy.

\citet{kim2011cpomdp} instead plan over belief/admissible-cost pairs, enforcing costs during pruning by a minimax quadratically constrained program or an approximate linear program. Their randomized policies can outperform our episode-level mixtures, which fix one information weight throughout each episode. Our SARSOP comparison estimates a feasible envelope from sampled usage-penalty policies, not a certified optimum. Sampling error and selection bias also affect that estimate (Appendix~\ref{app:cpomdp_details}).

The same reference construction does not reach EFE's operating region on RockSample[7,8]. A 12-point penalty sweep with depth-3 search yields zero or one check and rewards $9.5$ or $12.3$, versus EFE's $9.84$ checks (\url{experiments/run_rocksample_cpomdp_reference.py}). A usage penalty values a check through its short-horizon instrumental benefit, whereas the information weight credits gain locally. A deeper solver is needed for a useful reference.

Sequential Bayesian experimental design selects experiments for expected information gain \citep{lindley1956}, potentially through an amortized policy \citep{foster2021dad}. Our objective $R+wI$ balances that gain against task reward and sensing cost, with $w$ calibrated to expected sensing usage. It can therefore decline an informative experiment that an information-only objective selects.

\citet{kouw2026bethe} derive EFE as a stationary point of constrained Bethe free energy, with a multiplier on an internal information constraint. Their constraint differs both from our policy-level cumulative-information floor (Section~\ref{sec:budget_theory}) and from the sensing-usage cap. Their analysis does not supply our scale identities, grid crossings, mixtures or online budget controller. \citet{stocco2024recursive} instead use recursive, history-dependent dual ascent within constrained-POMDP tree search. They adjust per-node multipliers within a search, whereas our controller adjusts one scalar between episodes.

Offline calibration still requires a sweep, with no sampling advantage over direct weight tuning. Its input is an expected count or cost. The controller avoids that sweep only under Proposition~\ref{prop:pi5}'s conditions. Scale equivariance also transfers a directly tuned weight to $\alpha w$ on a rescaled grid, under the same tie assumptions. These are properties of the stated calibration procedure, not new generic duality results.''',
'Consolidate the expanded related-work discussion while preserving distinct primitives, policy classes, reference limitations and operational-cost disclosure.',
'All original primary citations remain. Distinctions from CPOMDP/PBVI, rational inattention, SAC, SBED, Bethe and per-node dual methods remain. RockSample failed reference retained with its numbers/path. No optimum, compute-saving, unique-equivariance or general tracking claim is introduced.')
add('theory-25',block('\\begin{example}[Destructive sensing can make naive information gain actively harmful]','Figure~\\ref{fig:state_preservation} isolates'),r'''\begin{example}[Destructive sensing can make naive information gain harmful]
\label{ex:destructive}
Let $s\in\{0,1\}$ have uniform prior and commit reward $r(\mathrm{Commit}_i,s)=+1$ if $i=s$, $-1$ otherwise. A test $a_D$ costs $c>0$, reveals the old state perfectly, $O(o=s\mid s,a_D)=1$, and then sets the state to $0$, $T(s'=0\mid s,a_D)=1$.

Ignoring the transition gives posterior $b'_o=\delta_o$ and one bit of information. At $w=1$ reward unit per bit,
\[
V_{\mathrm{naive}}(a_D)=-c+1+1=2-c.
\]
The correct posterior is instead
\[
b'_{o,T}(s')\propto\sum_s T(s'\mid s,a_D)O(o\mid s,a_D)b(s)\quad\Longrightarrow\quad b'_{o,T}=\delta_0
\]
for either report. For $o=1$ the two posteriors are disjoint point masses, so their KL divergence, and hence $\Delta_T$, is infinite. The post-transition state is already certain before seeing the report. A transition-aware EFE calculation therefore assigns zero epistemic value and gives
\[
V_{\mathrm{true}}(a_D)=-c+\max_i r(\mathrm{Commit}_i,0)=1-c.
\]
Immediate commitment has expected value zero. For $1<c<2$, the naive value recommends testing and the true value rejects it. Moreover, an agent that tests and commits according to the obsolete report realizes
\[
-c+\tfrac12r(\mathrm{Commit}_0,0)+\tfrac12r(\mathrm{Commit}_1,0)=-c,
\]
strictly worse than immediate commitment for every $c>0$. The example is checked in \texttt{tests/\allowbreak test\_\allowbreak destructive\_\allowbreak boundary.py}.
\end{example}''',
'Remove the repeated drilling metaphor and repeated interpretations while retaining every numerical and mathematical counterexample step.',
'Complete hidden-state/reward/observation/transition specification, timing, units, obsolete and correct posteriors, infinite diagnostic, naive and true values, strict ranking reversal, realized-policy loss for all positive costs, and executable check. The accompanying state-preservation figure is retained.')
path=root/'reviews/appendix_consolidation_2026-10-02/theory_proposals.json'
path.write_text(json.dumps(proposals,indent=2)+'\n')
print(json.dumps({'proposals':len(proposals),'old_words':sum(len(p['old'].split()) for p in proposals),'new_words':sum(len(p['new'].split()) for p in proposals),'removed_words':sum(len(p['old'].split())-len(p['new'].split()) for p in proposals),'jair_source_sha256':hashlib.sha256(s.encode()).hexdigest(),'lncs_variants':[p['id'] for p in proposals if 'old_lncs' in p]},indent=2))
