"""Hostile-AE R2/R3: target-matched frontier reference (results_budget_frontier_target_reference.csv)."""
from pathlib import Path

EDITS = [
    ("Against a sampled constrained reference, nominal pointwise paired intervals show reward shortfalls on eight of eleven distinct budgets. These intervals omit reference-selection uncertainty. The count replicates on fresh seeds but not every Diagnosis row does, and two Tiger comparisons are sensitive to rare errors.",
     "Against the best sampled reference policy that meets the same target, nominal pointwise paired intervals show reward shortfalls on two of eleven distinct budgets on held-out seeds and again on fresh seeds, and only Bandit's gap-budget shortfall recurs. Larger gaps to a usage-capped reference mostly reflect the cost of spending the target. These intervals omit reference-selection uncertainty."),
    ("but the selected mixtures can sacrifice reward relative to a constrained reference and need not be the best mixtures in the weight family.",
     "but the selected mixtures can sacrifice reward relative to spending less or to the best sampled policy meeting the same target, and need not be the best mixtures in the weight family."),
    ("The paired gap is mixture reward minus the same-stream cap-reference envelope, with seed-level SE. Its support and weights are fitted on those same seed means and held fixed for the SE, so intervals derived from this column are nominal pointwise plug-in summaries, as qualified in the text.",
     "The cap gap is mixture reward minus the same-stream cap-reference envelope, and the target gap is mixture reward minus the best sampled reference mixture whose usage equals $B$, each with seed-level SE. Reference supports and weights are fitted on those same seed means and held fixed for the SE, so intervals derived from these columns are nominal pointwise plug-in summaries, as qualified in the text."),
    ("Under that fitted comparison, negative $95\\%$ intervals exclude zero at nine of twelve attainable budgets, or eight of eleven distinct budgets after the Tiger duplicate is removed. The largest measured shortfall is $1.32$ on Bandit, about one fifth of its reference reward. A predeclared replication on ten fresh seeds again excludes zero at eight of eleven distinct budgets, but changes which Diagnosis budgets fall short (Appendix~\\ref{app:frontier_details}). Re-evaluation removes the stream mismatch but leaves selection bias from maximizing over noisy reference points.",
     "Under that fitted comparison, negative $95\\%$ intervals exclude zero at eight of eleven distinct budgets, counting Tiger's duplicate once. At seven budgets, every Tiger target, Bandit's three interior targets, and Diagnosis's largest, the cap is slack and the reference is the unconstrained reward optimum. A gap there combines the cost of spending $B$ with any inefficiency of the family. A predeclared target-matched reference separates the two. Subsidized SARSOP policies, with negative usage penalties, extend the sampled points above the unpenalized usage, and the reference becomes the best sampled mixture whose usage equals $B$ (\\texttt{run\\_\\allowbreak frontier\\_\\allowbreak target\\_\\allowbreak reference.py}). Against it, intervals exclude zero at two of eleven distinct budgets on the held-out seeds and again on ten fresh seeds, none of them slack. Only Bandit's gap-budget shortfall, $-0.59$ held out and $-0.50$ fresh, appears on both streams (Appendix~\\ref{app:frontier_details}). Both references are maxima over noisy sampled points, so selection bias remains."),
    ("Tiger requires an additional rare-event qualification. Neither the family nor any policy in the fitted reference support makes a wrong commit in the $500$ held-out episodes. Its paired gaps therefore measure only extra listening. A wrong commit costs $110$ relative to a correct one, and the canonical reference error rate is $0.6\\%$, equivalent to about $0.66$ expected reward. If the reference retained that rate while the family never erred, the smallest-budget shortfall would reverse and the middle-budget shortfall would nearly vanish. Only the largest Tiger shortfall is robust to that sensitivity calculation. The nominal intervals do not capture this rare-event uncertainty.",
     "Tiger's paired gaps measure only extra listening, since neither the family nor any policy in either reference support makes a wrong commit in the $500$ held-out episodes. A wrong commit costs $110$ relative to a correct one, and the canonical reference error rate of $0.6\\%$ is worth about $0.66$ expected reward, a rare-event uncertainty the nominal intervals do not capture."),
    ("The plug-in intervals therefore support the aggregate shortfall count and the Tiger and Bandit rows, not the identity of the Diagnosis budgets that fall short.",
     "The plug-in intervals therefore support the aggregate shortfall count and the Tiger and Bandit rows, not the identity of the Diagnosis budgets that fall short.\n\nThe cap reference is flat at the unpenalized reward wherever $B$ exceeds that policy's usage, which holds at seven of the eleven distinct budgets, so its shortfalls there include the cost of spending $B$. A predeclared target-matched reference removes that component (\\texttt{experiments/\\allowbreak run\\_\\allowbreak frontier\\_\\allowbreak target\\_\\allowbreak reference.py}, \\texttt{results\\_\\allowbreak cpomdp\\_\\allowbreak frontier\\_\\allowbreak subsidy.csv}, \\texttt{results\\_\\allowbreak budget\\_\\allowbreak frontier\\_\\allowbreak target\\_\\allowbreak reference.csv}). SARSOP is solved at eleven subsidized penalties $\\lambda=-c\\,s$, with $c$ the observation cost and $s$ from $0.1$ to $0.98$, so net observation reward stays negative while usage rises above the unpenalized level. Every sampled policy is evaluated on the held-out and fresh streams, after the committed policies reproduce their held-out rewards. At each budget the reference is the reward-maximizing mixture of sampled points whose held-out usage equals $B$, fitted on the held-out seeds and frozen for the fresh ones. At the four binding budgets it coincides with the cap reference. At the seven slack budgets it mixes the unpenalized policy with a subsidized one, and no interval excludes zero on either stream. The held-out target gaps there run from $-0.16\\pm0.12$ (Bandit, $B{=}5.51$) to $+0.08\\pm0.04$ (Tiger, $B{=}4.72$), and Diagnosis's largest target moves from $-1.10\\pm0.22$ against the cap reference to $-0.05\\pm0.16$. The two remaining held-out shortfalls are Diagnosis at $B{=}9.53$ and Bandit's gap budget. On the fresh seeds they are Diagnosis at $B{=}7.72$ ($-0.56\\pm0.24$) and Bandit's gap budget ($-0.50\\pm0.11$), so only Bandit's recurs. The reference is still a maximum over a finite set of approximately solved, noisily evaluated policies, so it estimates rather than bounds the best policy meeting each target."),
]
for name in ("full_paper_jair.tex", "full_paper.tex"):
    p = Path("paper") / name
    t = p.read_text()
    for old, new in EDITS:
        n = t.count(old)
        assert n == 1, (name, old[:70], n)
        t = t.replace(old, new)
    p.write_text(t)
    print(name, "ok")
